### ISSUE TITLE
Regressions 0.8.90-1

### ISSUE THREAD

**Issue by hugh-m** [AyatanaIndicators/ayatana-indicator-notifications#18]
I'm using ayatana-indicator-notifications 0.8.90-1 on Debian unstable installed via apt. For me there are a couple of changes that seem like regressions. Notifications are no longer truncated or wrapped, so long notifications spread the dialog across the screen, and, I can no longer dismiss saved notification unread with middle click on the icon. Ayatana-indicator-notifications is quite important to my workflow, so these changes are a definite inconvenience to me.

**Comment by sunweaver** [comment]
@hugh-m: could you please submit this bug report to Debian's bug tracker, as well? Debian 11 is currently being prepare from what we have in Debian testing/unstable and such a bug report in Debian BTS would be really helpful. I can then follow up on that and upload a fix (if we have any, need to check) to Debian testing/unstable before the release gates close. (Note: I am upstream and package maintainer in one person).

**Comment by sunweaver** [comment]
@trism @tari01: we don't seem to have a fix for this issue, yet. Does anyone of you have a clue how to fix this? I haven't observed such a behaviour, so far.

**Comment by tari01** [comment]
I will fix it, but not from within the indicator. Please see https://github.com/AyatanaIndicators/ayatana-indicator-datetime/pull/30#issuecomment-829056614

**Comment by sunweaver** [comment]
This issue will be resolved for the upcoming indicator release series 0.9.x, so closing.
