### ISSUE TITLE
Service works in the background but is not shown

### ISSUE THREAD

**Issue by Bob-YsPan** [AyatanaIndicators/ayatana-indicator-notifications#31]
I use Manjaro Linux and install it at AUR, after recent update (maybe few monthes ago),
the notification's icon gone but the service runnning in the background.

My desktop environment's specs:
MATE 1.26.0
MATE Panel 1.26.2
Ayatana Indicator 1.27.0

![The indicator bar](https://user-images.githubusercontent.com/46966555/210796188-9ce8f599-a7a2-4373-ab1d-d45cdef5f4a9.png)

![Service is running](https://user-images.githubusercontent.com/46966555/210796858-6d74fe83-41f5-4995-b6e9-7c61e1fc7d91.png)

**Comment by Bob-YsPan** [comment]
I found the solution... but seems like a little bug need to be fixed
It seems that the location specified by the auto-start's is different from the location where the installation package is actually installed.

The auto-start's is `/usr/local/libexec/ayatana-indicator-notifications/ayatana-indicator-notifications-service`

But the actual file is at `/usr/lib/ayatana-indicator-notifications/ayatana-indicator-notifications-service`

![image](https://user-images.githubusercontent.com/46966555/222321340-309ea874-0882-4ed4-9ceb-87b359637a27.png)

**Comment by trism** [comment]
I think I see the problem. You installed ayatana-indicator-notifications from AUR, which installs it to /usr/local, but later a package was added to the community repository, and I guess you auto-updated to that version, which installs to /usr. However an old autostart was copied to your local ~/.config/autostart and was overriding the system's version (maybe you modified startup apps at some point). Is your /etc/xdg/autostart/ayatana-indicator-notifications.desktop correct?

**Comment by Bob-YsPan** [comment]
Yeah... seems like the desktop file in the `/etc/xdg/autostart` are correct
![image](https://user-images.githubusercontent.com/46966555/224868291-5e434861-7518-4931-9d05-d2fa46925d11.png)
I tryied to delete the wrong files generated in `/home/ys-pan/.config/autostart` folder it fixed.
