### ISSUE TITLE
Notifications indicator not updating in arch linux.

### ISSUE THREAD

**Issue by tempuSr12** [AyatanaIndicators/ayatana-indicator-notifications#37]
the notifications indicator is not updating to show a different icon nor is it appearing in the history.
i used this aur to install it.
https://aur.archlinux.org/packages/ayatana-indicator-notifications
i already tried to reinstall the packages before but nothing changes.
i even did a fresh install of arch linux in a vm with no prior configuration or anything, just stock arch with the full mate desktop environment and the same problem still occurs in that vm.

**Comment by tari01** [comment]
1. Please verify that you have these (reboot after installation):

```
ayatana-ido
libayatana-indicator
libayatana-appindicator
```
2. If it still does not work, make sure you have added **Indicator Applet Complete** to the panel  (reboot after installation)

3. If still nothing, try launching it manually from the terminal:

` /usr/lib/ayatana-indicator-notifications/ayatana-indicator-notifications-service`

(The panel may reload)

Is there any suspicious output?

**Comment by tempuSr12** [comment]
nope, no output at all but its running and the icon is there, its just that it doesnt show up in the notifications history and the icon doesnt update to show a notification.
im using the command notify-send test and yet the notification is showing up, the notifications indicator isnt catching anything at all.

**Comment by tari01** [comment]
Scratch-scratch...

I am running Manjaro with MATE here, so it's safe to say we more-or-less have the same packages. On my end it works, so does in a Debian Testing WM. I honestly can't figure out what could be blocking the notifications on your end...

**Comment by tempuSr12** [comment]
maybe theres a modification thats simply missing on arch and i've heard that manjaro is a bit behind arch in terms of package updates.
after all, its in the aur so its expected that it should work just fine on arch but for some reason, its not working for me.
maybe try it on arch and see if you get the same result.

**Comment by tempuSr12** [comment]
yeah...
i just installed manjaro in a vm and updated everything, i then used pamac to install the indicators and im still having that same issue.

**Comment by tempuSr12** [comment]
https://github.com/AyatanaIndicators/ayatana-indicator-notifications/assets/166666317/052e8f18-be8a-4f0f-a045-4e2a3f33f778

https://github.com/AyatanaIndicators/ayatana-indicator-notifications/assets/166666317/184366e9-c40a-4bbb-8b6d-aafdd9cc6dc4
heres a comparison to show you what i really mean.

**Comment by tari01** [comment]
Here's my test: Current Manjaro MATE image, everything updated through Pamac, and used Pamac to install ayatana-ido,
libayatana-indicator, libayatana-appindicator, ayatana-indicator-notifications, and mate-indicator-applet.

![Manjaro](https://github.com/AyatanaIndicators/ayatana-indicator-notifications/assets/9939853/09cd4228-52d0-4227-94e0-938b1dbc5bb7)

**Comment by tari01** [comment]
Ha! I think I got it. I bet you have installed `dbus-broker-units` instead of `dbus-daemon-units`?

**Comment by tempuSr12** [comment]
yes, that was the issue.
i installed dbus-daemon-units and now the notifications are working as expected, maybe make this package a required dependency in the aur?
note that it kinda freezes everything for a short while if you do install it so maybe do with caution.
