### ISSUE TITLE
add XDG autostart file(?)

### ISSUE THREAD

**Issue by sunweaver** [AyatanaIndicators/ayatana-indicator-notifications#6]
Additionally to #5 we should add an XDG autostart file (for non-systemd platforms).

@tari01: feedback? comments?

**Comment by tari01** [comment]
Hmm... The indicator base already sort-of depends on systemd. I know there are people out there that strongly oppose systemd and use init scripts in their custom OS-es, but aren't all stock builds nowadays shipping with systemd?

**Comment by sunweaver** [comment]
References:
 <AyatanaIndicators/ayatana-indicator-notifications/issues/6@github.com>
 <AyatanaIndicators/ayatana-indicator-notifications/issues/6/671306259@github.com>
 
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: base64
Date: Mon, 10 Aug 2020 11:55:05 +0000
Message-ID: <6buxc.qeujs0.2u2klh-qmf@grimnir.das-netzwerkteam.de>
MIME-Version: 1.0

SGksDQoNCkFtIE1vbnRhZywgMTAuIEF1Z3VzdCAyMDIwIHNjaHJpZWIgUm9iZXJ0IFRhcmk6DQo+
IEhtbS4uLiBUaGUgaW5kaWNhdG9yIGJhc2UgYWxyZWFkeSBzb3J0LW9mIGRlcGVuZHMgb24gc3lz
dGVtZC4gSSBrbm93IHRoZXJlIGFyZSBwZW9wbGUgb3V0IHRoZXJlIHRoYXQgc3Ryb25nbHkgb3Bw
b3NlIHN5c3RlbWQgYW5kIHVzZSBpbml0IHNjcmlwdHMgaW4gdGhlaXIgY3VzdG9tIE9TLWVzLCBi
dXQgYXJlbid0IGFsbCBzdG9jayBidWlsZHMgbm93YWRheXMgc2hpcHBpbmcgd2l0aCBzeXN0ZW1k
Pw0KPiANCg0KTXkgc3BlY2lhbCB1c2UgY2FzZSBpcyBNQVRFIG9uIG5vbi1MaW51eCBzeXN0ZW1z
IChlLmcuIERlYmlhbiBHTlUva0ZyZWVCU0QgYW5kIERlYmlhbiBHTlUvSHVyZCkuIFRoZSBnb2Fs
IGZvciBNQVRFIGluIERlYmlhbiBpcyB0byBiZSB1c2FibGUgb24gcmVhbGx5IGFsbCBhcmNoaXRl
Y3R1cmVzLiBBcyBNQVRFIHdpdGggSW5kaWNhdG9ycyBzaGFsbCBiZSBhIHBvc3NpYmxlIGRlZmF1
bHQgaW4gRGViaWFuLCBJJ2QgbGlrZSB0byBoYXZlIEF5YXRhbmEgSW5kaWNhdG9ycyBhdmFpbGFi
bGUgYWxzbyBvbiB0aGUgbm9uLUxpbnV4IHBsYXRmb3Jtcw0KDQoNCi0tIA0KR2VzZW5kZXQgdm9u
IG1laW5lbSBGYWlycGhvbmUgKHBvd2VyZWQgYnkgU2FpbGZpc2hPUyk=

**Comment by sunweaver** [comment]
base64-decoded...

My special use case is MATE on non-Linux systems (e.g. Debian GNU/kFreeBSD and Debian GNU/Hurd). The goal for MATE in Debian is to be usable on really all architectures. As MATE with Indicators shall be a possible default in Debian, I'd like to have Ayatana Indicators available also on the non-Linux platforms

**Comment by tari01** [comment]
In that case it's not even up for debate - XDG autostart files should be included (through conditional packaging?)

**Comment by sunweaver** [comment]
Hi,

On  Di 11 Aug 2020 17:27:42 CEST, Robert Tari wrote:

> In that case it's not even up for debate - XDG autostart files  
> should be included (through conditional packaging?)

my idea is to have XDG autostart .desktop files but have all services  
disabled by default. The user can then enable the indicators that are  
wanted via the autostart settings dialog of the desktop environment.

Feedback?

Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler Str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4351) 850 8940

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by tari01** [comment]
Sounds good to me. Perhaps I would enable the minimal defaults: session + datetime + sound + network + messages. Messages will not show up until an application register itself there.

**Comment by sunweaver** [comment]
The point is that most desktop envs should start system indicators via systemd. So, for builds with systemd, we need to disable all XDG autostarted indicators. If a desktop env does not have systemd support for AI yet (i.e. it does not request the new ayatana-indicators.target), then XDG autostart should be possible.

Once a desktop env has been switched to ayatana-indicators.target/systemd, then we should drop that desktop env from OnlyShowIn. See (for MATE):
https://github.com/mate-desktop/mate-indicator-applet/issues/63

Unfortunately, MATE handles the disabling of autostart service in a non-portable way, see:
https://github.com/mate-desktop/mate-session-manager/issues/260

Furthermore, all indicators have NoDisplay=true currently. With MATE 1.24 and later, such  .desktop files will be hidden from the mate-session-properties dialog.

I still need to breed on this. How to best expose indicators via XDG autostart on non-systemd systems (certainly a build time thing) and how to handle the transition from XDG autostart to systemd/ayatana-indicators.target for desktop envs that still use XDG autostart. However, if systemd is unavailable, then XDG autostart should be the way to go for all desktop envs (that are able to run on non-systemd systems).

**Comment by sunweaver** [comment]
The notification indicator is not an NG indicator (which I always thought it is...). Thus, no autostart nor systemd start required.
